export { DiffSplitIcon, DiffUnifiedIcon, DiffBackgroundIcon } from './DiffIcons'
export { registerCraftShikiThemes } from './registerShikiThemes'
export { ShikiCodeViewer, type ShikiCodeViewerProps } from './ShikiCodeViewer'
export { ShikiDiffViewer, type ShikiDiffViewerProps, getDiffStats } from './ShikiDiffViewer'
export { UnifiedDiffViewer, type UnifiedDiffViewerProps, getUnifiedDiffStats } from './UnifiedDiffViewer'
export { DiffViewerControls, type DiffViewerControlsProps } from './DiffViewerControls'
